{"name": "Test concurrent user sessions - Bug Discovery", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3\n +  where 2 = len([{'text': 'User 0 text'}, {'text': 'User 1 text'}])", "trace": "C:\\Workspace-local\\PlainsightAI-takehome\\qa_tests\\end_to_end\\test_user_scenarios.py:205: in test_concurrent_user_sessions_bug\n    ???\nE   AssertionError: assert 2 == 3\nE    +  where 2 = len([{'text': 'User 0 text'}, {'text': 'User 1 text'}])"}, "description": "Bug discovery: concurrent user sessions cause data conflicts", "start": 1751312138892, "stop": 1751312138993, "uuid": "9efc6078-4c6b-4033-94f4-643f52af375d", "historyId": "901e034f68034a7f520e209703818e77", "testCaseId": "901e034f68034a7f520e209703818e77", "fullName": "end_to_end.test_user_scenarios.TestCompleteUserScenarios#test_concurrent_user_sessions_bug", "labels": [{"name": "epic", "value": "OpenFilter QA"}, {"name": "severity", "value": "blocker"}, {"name": "feature", "value": "User Scenarios"}, {"name": "story", "value": "Complete User Workflows"}, {"name": "tag", "value": "bug_discovery"}, {"name": "tag", "value": "pyramid_functional"}, {"name": "tag", "value": "functional"}, {"name": "parentSuite", "value": "end_to_end"}, {"name": "suite", "value": "test_user_scenarios"}, {"name": "subSuite", "value": "TestCompleteUserScenarios"}, {"name": "host", "value": "fealfr"}, {"name": "thread", "value": "30472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "end_to_end.test_user_scenarios"}]}