{"name": "test_filter_cleanup_exception_handling", "status": "passed", "description": "Test cleanup behavior when exceptions occur.", "start": 1751312149647, "stop": 1751312149647, "uuid": "8cdc51f7-e4fe-4c33-af91-247259b82577", "historyId": "ce44dac1afa9b40edff1b031f0f4b436", "testCaseId": "ce44dac1afa9b40edff1b031f0f4b436", "fullName": "unit.test_filter_clean.TestFilterCleanup#test_filter_cleanup_exception_handling", "labels": [{"name": "tag", "value": "bug_discovery"}, {"name": "tag", "value": "pyramid_unit"}, {"name": "tag", "value": "unit"}, {"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_filter_clean"}, {"name": "subSuite", "value": "TestFilterCleanup"}, {"name": "host", "value": "fealfr"}, {"name": "thread", "value": "30472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_filter_clean"}]}